### ISSUE TITLE
RViZ no Visualization in world frame and path

### ISSUE THREAD

**Issue by honeytung** [MIT-SPARK/Kimera-Multi#6] opened 2023-08-08 22:03 UTC
Hello, thank you for sharing this great work! I was trying to run the example with the campus outdoor dataset but there are no visualization showing up in RViZ. All the setup and code builds with no errors and the command `CATKIN_WS=<path-to-catkin-ws> DATA_PATH=<path-to-campus-outdoor-data-folder> LOG_DIR=<path-to-log-folder> tmuxp load 1014-example.yaml` also ran fine with no errors.

However, inside RViZ it cannot find the fixed frame `world` and in the terminal, it also shows 0 loop-closures for the entire duration of the rosbags. I wonder if I missed anything and any suggestions would be appreciated! Thanks!

I am running ROS noetic.

![Screenshot from 2023-08-08 14-54-23](https://github.com/MIT-SPARK/Kimera-Multi/assets/9246485/b7c98eab-b89b-456d-a216-05d6723b9ce3)
![Screenshot from 2023-08-08 14-54-47](https://github.com/MIT-SPARK/Kimera-Multi/assets/9246485/5f82d66e-7ecd-46ec-bbcc-d22bd26ca3dc)

**Comment by yuluntian** [comment] 2023-08-15 03:07
Hi @honeytung, thank you for using our system. It looks like the loop closure module is not functioning as intended for you, and as a result, the back-end is unable to run and show the final trajectory estimates in the global frame. 

Could you post the log generated by each robot's loop closure module, so that we can further investigate this issue? For example, the log of the first robot should be located at `LOG_DIR/acl_jackal/distributed/lcd_log.csv`.

**Comment by honeytung** [comment] 2023-08-15 06:02
Hello @yuluntian, thank you for your reply! Here are the logs for each robot.
Most of the `lcd_log.csv` files do not contain any values or it is full of zeros. Thanks for your help!

[logs.zip](https://github.com/MIT-SPARK/Kimera-Multi/files/12341601/logs.zip)

**Comment by yuluntian** [comment] 2023-08-16 19:31
Thank you for sharing the logs. It seems that the `lcd_logs.csv` files are incomplete, and all `odometry_poses.csv` files (which logs odometry from Kimera-VIO)  are empty. The following might be useful things to check:

- Check that Kimera-VIO is running (the `vio` window inside tmux), and that you can visualize its trajectory estimates (`ROBOT_NAME/kimera_vio_ros/optimized_trajectory` topic) in rviz
- Make sure to decompress the rosbags, and play the bags until completion: based on `LOG_DIR/acl_jackal/distributed/lcd_log.csv`, it seems only the first 70 sec are logged right now.
- For debugging, it might be useful to decrease the rosbag playback rate. This can be done by changing the `RATE` arg in `1014_example.yaml`, e.g., `RATE=0.1`

**Comment by honeytung** [comment] 2023-08-18 23:34
Thanks, @yuluntian for your help! I was able to find out the issue. It turns out I was missing one package required for Kimera-VIO (the `image_transport_plugins` package).

I am able to see the RViZ result after running rosbags for the first two robots (`acl_jackal` and `acl_jackal2`). Just to confirm, is it the expected result from the loop_closure_detection?
![Screenshot from 2023-08-18 16-25-38](https://github.com/MIT-SPARK/Kimera-Multi/assets/9246485/21aaf416-4e5f-4c2b-8d95-b8012d380428)

I noticed that even when running with two robots, my system RAM usage will be approaching almost 30GB. What would be the estimated minimum system requirement for running with six robots?

**Comment by yuluntian** [comment] 2023-08-19 18:25
Great! Yes, those are the expected trajectory estimates for the first two robots.

About RAM usage: the ideal way to run Kimera-Multi is to run each robot on a separate machine. This way the RAM usage on each machine will be much lower. However, the current public release doesn't have an example for this yet, because we are still waiting for approval to release the inter-robot/machine communication module.

That being said, 30GB still sounds a little high just for two robots. Just to check, did you launch the full six robots example (but only played the bags for the first two robots)? This might explain the 30GB because the other four robots also take up RAM even if they are not processing any data.

**Comment by honeytung** [comment] 2023-08-22 21:42
Thanks @yuluntian! I ran the example with only the commands for `robot0` and `robot1` (deleted all other commands for the 4 robots). The total RAM + Swap usage is approximately 35GB.

![Screenshot from 2023-08-22 14-29-07](https://github.com/MIT-SPARK/Kimera-Multi/assets/9246485/6c8f5a19-3f95-4f9b-bc19-ee98cf27ff57)

Additionally, I noticed that the example file does not launch kimera-semantics for the 3D mesh construction. Are there any commands that I am missing from the `.yaml` file that I should be launching?

**Comment by shubham-kumar1410** [comment] 2023-08-23 02:58
Hey,
I am facing a similar issue with RViz showing no path. I am running the algorithm with 2 robots with decompressed bags.

I checked with the above comments and it seems that the topic /acl_jackal/kimera_vio_ros/optimized_trajectory does publish the path however, the final path from /acl_jackal/dpgo_ros_node/path has no messages.

I am running this with ROS Melodic. Any help would be appreciated. Thanks

**Comment by yuluntian** [comment] 2023-08-25 15:02
@honeytung Thanks! I'm going to close this because the main issue is addressed.

Re RAM: currently, we don't have plans for improving the RAM usage, so if this becomes a bottleneck, the best way forward would be to try the multi-machine setup when that's released.

Re mesh reconstruction: you're right the example does not launch kimera-semantics and I will need to get back to you on this. Please open a new issue if needed and we can discuss from there.

**Closed as completed by yuluntian** 2023-08-25 15:02 UTC
